---
name: PyInstaller

on:  # yamllint disable-line rule:truthy
  push: null
  pull_request: null

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12.3

    - run: pip install --no-deps -r requirements.txt pyinstaller
    - run: pyinstaller --onefile check_revocation.py
    # Optionally verify that it works (provided that it does not need user interaction)
    - run: ./dist/check_revocation/check_revocation.py
    - uses: actions/upload-artifact@v4
      with:
        path: dist/*
