---
name: PyInstaller

on:
  push:
#    branches: master

permissions: { }

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install requirements
        run: |
          pip install --no-deps -r requirements.txt pyinstaller pywin32-ctypes
      - name: Run PyInstaller
        run: |
          pyinstaller --onefile check_revocation.py
      - uses: actions/upload-artifact@v4
        with:
          name: Check Revocation
          path: dist/check_revocation.exe

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.head_commit.message }}
          release_name: ${{ github.event.head_commit.message }}
          overwrite: true
          body: |
            Test Release v1.0.0
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: dist/check_revocation.exe
          asset_name: check_revocation-amd64.exe
          asset_content_type: application/zip
